version: '3.8'  # Specify the version of Docker Compose

services:
  proxywala:
    build:
      context: .  # Build the Dockerfile in the current directory
    ports:
      - "127.0.0.1:5000:5000"  # Bind port 5000 on localhost to port 5000 in the container
    environment:
      - FLASK_ENV=development  # Set the environment to development
